using PharmacyInventoryDispensingSystem.Domain.Common;
using PharmacyInventoryDispensingSystem.Domain.Common.Results;
using PharmacyInventoryDispensingSystem.Domain.Entities.Dispenses;
using PharmacyInventoryDispensingSystem.Domain.Entities.Patients;
using PharmacyInventoryDispensingSystem.Domain.Enums;

namespace PharmacyInventoryDispensingSystem.Domain.Entities.Prescriptions;

public sealed class Prescription : AuditableEntity
{
    /// <summary>
    /// Unique prescription number automatically generated by the system.
    /// Format: RX- followed by a 6-digit sequential number.
    /// Example: RX-000001.
    /// </summary>
    public string PrescriptionNumber { get; set; } = string.Empty;

    public Guid PatientId { get; set; }

    public string DoctorId { get; set; } = string.Empty;

    public DateOnly ValidFrom { get; set; }

    public DateOnly ValidTo { get; set; }

    public PrescriptionStatus Status { get; set; } 

    public string? Notes { get; set; }

    public Patient Patient { get; set; } = null!;

    public ICollection<PrescriptionItem> Items { get; set; } = [];
       

    public ICollection<Dispense> Dispenses { get; set; } = [];
        

    /// <summary>
    /// is used later to check whether a specific prescription is valid on a given date by verifying 
    /// that its status is Active and that the date falls within its validity period
    /// </summary>
    /// <param name="asOf"></param>
    /// <returns></returns>
    public bool IsValidOn(DateOnly date) =>
        Status == PrescriptionStatus.Active &&
        date >= ValidFrom &&
        date <= ValidTo;



}
